FROM node:20-alpine

# Install OpenSSL and required libraries for Prisma compatibility
RUN apk add --no-cache openssl openssl-dev libc6-compat

WORKDIR /app
COPY package.json pnpm-workspace.yaml prisma ./
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate
RUN pnpm i
RUN pnpm prisma:generate
COPY apps/worker ./apps/worker
COPY packages ./packages
WORKDIR /app/apps/worker
RUN pnpm install
CMD ["pnpm","dev"]
